---
title: "Project 05b -- Instructions (14h30 Section)"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r, include=FALSE}
library(tidyverse)
library(ggrepel)
library(smodels)

theme_set(theme_minimal())
options(pillar.min_character_chars = 15)
Sys.setlocale("LC_TIME", "en_US.UTF-8")
```

**Due Date**: 22 April 2021


## General Instructions

This page outlines the instructions for the first project. You should
have a file `project05b.Rmd` in your RStudio workspace where you can
work on the project. I find that students prefer having a consistent
format for the projects, so I will attempt to keep the format the same
throughout the semester.

On the due-date, your group is responsible for completing three elements:

1. A short (about one-page single spaced) description of your work answering
a subset of the questions below. Please submit as a Google Doc in your shared
group Google Drive folder.
2. A Google Slides presentation of your results, also submitted in your shared
drive folder.
3. Giving a presentation based on your slide show. This should be 8-10 minutes
in length. I suggest having one member drive the slides and the others rotate
describing the results.

As described on the syllabus, the project will be graded as either Satisfactory
or Unsatisfactory. I will provide additional feedback that you can address in
the next project.

## Specific Instructions

The data for this project comes from new articles from a collection of news
sources surrounding the weeks leading up to and following the 2016 U.S.
presidential election. The original data was collected and distributed by the
website
[components.one](https://components.one/datasets/all-the-news-articles-dataset).
Each group has been assigned different sets of three weeks to work with.

The idea of this data set is to capture elements of all four of the previous
projects. You should already have an idea of what projects in the class look
like and what your classmates and I expect from a good presentation. You can
pick any aspect(s) of the collection to look at: classifying the different
news outlets, building topic models, or clustering the different sources.

Note that this data set is a significantly more messy than the others we have
worked with this semester. For example, the data often includes extra headers
and footers. You may need to think about how to avoid this in your analysis.

## Groups

Each group is working with a set of news articles from different three week
periods leading up to the 2016 presidental election. You should be able to
download your data set from within the `project05b.Rmd` file.

**Group 1**: `news_time_1` => 2016-06-13 to 2016-07-03

**Group 2**: `news_time_2` => 2016-07-04 to 2016-07-24

**Group 3**: `news_time_3` => 2016-07-25 to 2016-08-14

**Group 4**: `news_time_4` => 2016-08-15 to 2016-09-04

**Group 5**: `news_time_5` => 2016-09-05 to 2016-09-25

**Group 6**: `news_time_6` => 2016-09-26 to 2016-10-16

**Group 7**: `news_time_7` => 2016-10-17 to 2016-11-06

**Group 8**: `news_time_8` => 2016-11-07 to 2016-11-27

## Notes

While working through the project, I typically find that many groups ask for
help writing the same bits of code. Any notes that I want to share about how
to do specific tasks will be added here as we work through the project.
