---
title: "Notebook 09: Local Models (KNN and GBM)"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r message=FALSE}
library(tidyverse)
library(forcats)
library(ggrepel)
library(smodels)
library(cleanNLP)
library(Matrix)
library(xgboost)
library(stringi)

theme_set(theme_minimal())
options(dplyr.summarise.inform = FALSE)
options(width = 77L)
options(sparse.colnames = TRUE)
```

## Five British Authors

Robert Louis Stevenson

```{r, message=FALSE}
stylo <- read_csv("data/stylo_uk.csv") %>%
  mutate(train_id = if_else(runif(n()) < 0.6, "train", "valid"))
token <- read_csv("data/stylo_uk_token.csv.gz")
```

```{r}
X <- token %>%
  sm_ngram(n = 3, n_min = 1, token_var = "upos") %>%
  cnlp_utils_tf(doc_set = stylo$doc_id,
                min_df = 0.005,
                max_df = 1,
                max_features = 10000,
                token_var = "token")
```

```{r}
X[1:10, c(1:2, 51:52, 1000:1001)]
```



### K-nearest neighbors

```{r}
y <- stylo$author
y_train <- y[stylo$train_id == "train"]
y_valid <- y[stylo$train_id == "valid"]
X_train <- X[stylo$train_id == "train",]
X_valid <- X[stylo$train_id == "valid",]
```

```{r}
library(FNN)
y_hat <- knn(X_train, X, y_train, k = 4)
```

```{r}
stylo %>%
  mutate(author_pred = y_hat) %>%
  group_by(train_id) %>%
  summarize(mean(author_pred == author))
```

```{r}
stylo %>%
  mutate(author_pred = y_hat) %>%
  select(author, author_pred, train_id) %>%
  table()
```


```{r}
library(FNN)
y_hat <- knn(X_train, X, y_train, k = 10)

stylo %>%
  mutate(author_pred = y_hat) %>%
  group_by(train_id) %>%
  summarize(mean(author_pred == author))
```

### Decision Trees



### Gradient Boosted Trees


```{r}
author_set <- unique(stylo$author)
y <- (match(stylo$author, author_set) - 1L)
```



```{r}
y_train <- y[stylo$train_id == "train"]
y_valid <- y[stylo$train_id == "valid"]
X_train <- X[stylo$train_id == "train",]
X_valid <- X[stylo$train_id == "valid",]

data_train <- xgb.DMatrix(data = X_train, label = y_train)
data_valid <- xgb.DMatrix(data = X_valid, label = y_valid)

watchlist <- list(train=data_train, valid=data_valid)
```

```{r}
model <- xgb.train(data = data_train,
                 max_depth = 3, eta = 0.05, nthread = 2,
                 nrounds = 10, objective = "multi:softmax",
                 watchlist = watchlist, verbose = 10, num_class = 5)
```

```{r}
model <- xgb.train(data = data_train,
                 max_depth = 3, eta = 0.03, nthread = 2,
                 nrounds = 100, objective = "multi:softmax",
                 watchlist = watchlist, verbose = FALSE, num_class = 5)
```


```{r}
y_hat <- author_set[predict(model, newdata = X) + 1]

stylo %>%
  mutate(author_pred = y_hat) %>%
  group_by(train_id) %>%
  summarize(mean(author_pred == author))
```


```{r}
importance_matrix <- xgb.importance(model = model)
importance_matrix
```

```{r}
y_hat <- author_set[predict(model, newdata = X) + 1]

stylo %>%
  mutate(pred = y_hat) %>%
  select(author, pred, train_id) %>%
  table()
```










